version: '3.3'
services:
  proxy:
    container_name: proxy
    image: nginx:1.23.2
    volumes:
      - newTarget:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    ports:
      - 8080:8080
    # networks:
    #   - back-proxy

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - newTarget:/sources-target
    # networks:
    #   - back-proxy


# networks:
#   back-proxy: {}

volumes:
  newTarget: {}

