FROM alpine:3.15 as stage
RUN apk update
RUN apk add npm

RUN mkdir project
COPY project /project

WORKDIR /project/flask-app
VOLUME [ "/project/flask-app" ]
RUN npm install
RUN npm run build


FROM alpine:3.15 as build
RUN apk add python2  && \
             python -m ensurepip &&  \ 
             pip install --upgrade pip

COPY --from=stage /project /project
WORKDIR /project/flask-app
RUN pip install -r requirements.txt

CMD [ "python", "./app.py" ]