FROM alpine:3.15 as stage
RUN apk update && \
    apk add python2 && \
    python -m ensurepip && \
    pip install --upgrade pip && \
    apk add npm

RUN mkdir /project
COPY project /project

WORKDIR /project/flask-app
RUN npm install && \
    pip install -r requirements.txt && \
    npm run build

CMD ["python2", "./app.py"]