version: '3.3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - 8080:8080
    networks:
      - app-net

  proxy:
    container_name: proxy
    image: nginx:latest
    networks:
      - app-net
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - app

networks:
  app-net:

# volumes:
#   conf: