FROM alpine:3.15
RUN apk update
RUN apk add python2
RUN python -m ensurepip
RUN pip install --upgrade pip
RUN apk add npm

RUN mkdir /project
COPY project /project

WORKDIR /project/flask-app
RUN npm install
RUN pip install -r requirements.txt
RUN npm run build 

CMD ["python2", "app.py"]
