version: '3.3'
services:
# LAVAGNA DB
  lavagna-db-thin:
    container_name: lavagna-db-thin
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD : "admin"
      MYSQL_DATABASE : "lavagna"
      MYSQL_PASSWORD : "password"
      MYSQL_USER : "lavagna"
    volumes:
      - data-vol-thin:/var/lib/mysql
    networks:
      - db-net-thin
    healthcheck:
      test: ["CMD","mysqladmin", "ping", "-h", "lavagna-db-thin", "-u", "root", "-padmin"]
      interval: 10s
      timeout: 30s
      retries: 5

# LAVAGNA 
  lavagna-thin:
    container_name: lavagna-thin
    build:
      context: .
      dockerfile: Dockerfile.thin
    networks:
      - db-net-thin
      - proxy-net-thin
    depends_on:
      lavagna-db-thin:
        condition: service_healthy
    # ports:
    #   - 8080:8080

#Lavagna Proxy
  lavagna-proxy-thin:
    container_name: lavagna-proxy-thin
    image: nginx:1.23.2
    networks:
      - proxy-net-thin
    volumes:
      - ./nginx.d/nginx.conf:/etc/nginx/nginx.conf
      - ./src/main/webapp:/usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - lavagna-thin
        # condition: service_healthy


  lavagna-docs-proxy:
    build: 
      context: .
      dockerfile: Dockerfile.docs
    ports: 
      - 8081:45001


networks:
  db-net-thin:
    # driver: bridge
  proxy-net-thin:
    # driver: bridge

volumes:
  data-vol-thin:
