# Fat Image
FROM maven:3.6.3-openjdk-8
WORKDIR /app
COPY . .
COPY entrypoint.sh /usr/local/bin
RUN chmod +x /usr/local/bin/entrypoint.sh

RUN mvn verify -Dmaven.skip.test=true

ENV DB_DIALECT MYSQL
ENV DB_URL jdbc:mysql://lavagna-db:3306/lavagna?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
ENV DB_USER lavagna
ENV DB_PASS "password"
ENV SPRING_PROFILE dev


ENTRYPOINT [ "entrypoint.sh" ]