version: "3.3"
services:
  cowsay:
    environment:
      - NODE_ENV=development
    build:
      context: ./src
    expose: 
      - "5550"
    ports:
      - "5550:5550"

  nginx:
    restart: always
    build:
      context: ./nginx
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/
    ports:
      - "5555:80"
