version: '3.6'
services:

  jenkins:
    container_name: jenkins
    # image: jenkins/jenkins:lts-jdk11
    build: 
     context: .
     dockerfile: Dockerfile.jenkins
    restart: on-failure
    ports:
      - '8000:8080'
      - '50000:50000'
      - '4000:80'
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
#      - /usr/bin/docker:/usr/bin/docker
    hostname: jenkins
    networks: 
      - jenkins-gitlab-net
    depends_on:
      gitlab:
        condition: service_healthy
      
  gitlab:
    container_name: gitlab
    image: 'gitlab/gitlab-ce'
    restart: always
    hostname: 'gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
         gitlab_rails['gitlab_root_password'] = "1234567890"
    #  GITLAB_ROOT_PASSWORD: ${GITLAB_ROOT_PASSWORD}
    ports:
      - '80:80'
      - '3030:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      - jenkins-gitlab-net

networks:
  jenkins-gitlab-net:

volumes:
 jenkins_home: {}
