version: '3.6'
services:

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts-jdk11
    restart: on-failure
    ports:
      - "8080:8080"
      - "5000:5000"
      - "4000:4000"
    volumes:
      - jenkins_home:/var/jenkins_home
    hostname: jenkins
    networks: 
      - jenkins-gitlab-net

  web:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'ec2-52-25-253-13.us-west-2.compute.amazonaws.com'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '3030:22'
      # - '22:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      - jenkins-gitlab-net

networks:
  jenkins-gitlab-net:

volumes:
  jenkins_home: {}
